evergreen-ci/utility

- parsing.go
fix ReadYAML typo
[EVG-7915 PR ](https://github.com/evergreen-ci/evergreen/pull/3611)
> EVG-7915 : Allow passing a YAML document to host.create

- checksum.go
- checksum_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1351
This is taken from pail so we can re-use these in the jasper file dependency caching.
> MAKE-1351: add file checksum functions

- file.go
- file_test.go
JIRA: https://jira.mongodb.org/browse/EVG-8930
`BuildFileList` finds files within a directory but assumed that the implementation would always be based on gitignore-style file matching. This one is meant to allow alternative include filter implementations aside from gitignore. It also provides support for file exclusion filters.
* Refactor `BuildFileList` into `FileListBuilder` to allow include/exclude file filters.
* Export gitignore-based file matcher.
> EVG-8930: make file list builder more usable

- optional.go
JIRA: https://jira.mongodb.org/browse/EVG-13920
Since a lot of libraries are using pointers as optionals, I moved them here so all the libraries can share it.
> EVG-13920: add value-pointer conversion methods

- time.go
JIRA: https://jira.mongodb.org/browse/EVG-14116
Round BSON time according to the [docs](https://docs.mongodb.com/manual/reference/bson-types/#date).
> EVG-14116: add helper method to convert time to BSON timezone and precision

- http.go
- retry.go
- retry_test.go
- slice_test.go
Jira: https://jira.mongodb.org/browse/EVG-14733
* Move the logic to perform [retrying with exponential backoff + jitter from Evergreen's util package](https://github.com/evergreen-ci/evergreen/blob/main/util/retry.go) to here. I tidied it up a bit, so it doesn't match the util package exactly.
* Fix an unrelated test that checked for an empty slice instead of nil slice.
> EVG-14733: move retry functionality from Evergreen

- http.go
Jira: https://jira.mongodb.org/browse/EVG-14988
`RetryRequest` now uses the same logic as `Retry` since they both do retries with exponential backoff. The only difference is that `RetryRequest` is supposed to specifically handle an HTTP request.
> EVG-14988: clean up RetryRequest

- http.go
Jira: https://jira.mongodb.org/browse/EVG-14988
`Retry` requires the function to return an error in order to retry.
> EVG-14988: fix RetryRequest

- http.go
- makefile
Jira:
https://jira.mongodb.org/browse/EVG-15479
https://jira.mongodb.org/browse/EVG-15495
* Remove GO_BIN_PATH. CI tests now depend on GOROOT to tell them which Go version to use and which Go binary to use.
* Set the GOLANGCI_LINT_CACHE, which is used to control where golangci-lint caches information. By default, golangci-lint will use the user's cache directory (usually in the home directory). This prevents the CI linter from writing outside of the working directory.
* Fix setting the PATH variable for the linter.
* Clean up and standardize the makefile.
> EVG-15479, EVG-15495: remove GO_BIN_PATH and fix linter PATH

- http.go
- http_test.go
JIRA: https://jira.mongodb.org/browse/EVG-15242
This is a convenience implementation of the `http.Handler` interface for mock HTTP servers. Mostly will be used with `httptest.NewServer`.
> EVG-15242: Mock HTTP Handler implementation

- makefile
- slice.go
- slice_test.go
Jira: https://jira.mongodb.org/browse/EVG-17128
* Ported over another [string slice helper function](https://github.com/evergreen-ci/evergreen/blob/d12940c1609c7e47d27c9a1fddf7ee2972a743a2/util/strings.go#L99-L108) from Evergreen.
* Switch the linter download away from Goreleaser for [EVG-16930](https://jira.mongodb.org/browse/EVG-16930).
> EVG-17128, EVG-16930: port over more string slice methods from Evergreen and deprecate Goreleaser

- hash.go
- hash_test.go
Jira: https://jira.mongodb.org/browse/EVG-16911
This basically just lifts [the code straight from Cocoa](https://github.com/evergreen-ci/cocoa/blob/9c40afd9b130ff985d1f320544c5c04353016eca/ecs_pod_creator.go#L399-L418) and puts it in the common helper library since Evergreen will need similar logic.
> EVG-16911: migrate hashing helper from Cocoa

- buffer.go
Jira: https://jira.mongodb.org/browse/EVG-17046
I'm moving [a useful helper type to wrap `bytes.Buffer`](https://github.com/mongodb/jasper/blob/5925eb396fb86e4009554bed4fa5592bbc7f2ee3/util/buffer.go#L9) out of Jasper and into the general-purpose utility module since it's a miscellaneous and multi-purpose convenience feature. Going to actually use it in Evergreen + update usages in Jasper once this is merged.
> EVG-17046: move thread-safe buffer from Jasper to utility

- http.go
- http_test.go
[EVG-19189](https://jira.mongodb.org/browse/EVG-19189)
I'm planning to pass in a client that creates traces for external calls. This PR will allow me to reconfigure the client pool to use the supplied client factory. If you don't configure it it will continue to do the same thing it's doing now.
> EVG-19189 make base client configurable

- http.go
[EVG-17142](https://jira.mongodb.org/browse/EVG-17142)
Make the default transport/client public so they can be used in https://github.com/evergreen-ci/evergreen/pull/6677
> EVG-17142 expose defaults

- time.go
[DEVPROD-3947](https://jira.mongodb.org/browse/DEVPROD-3947)
Related to https://github.com/evergreen-ci/evergreen/pull/7564.
Add some simple constants to help with time math.
> DEVPROD-3947: add time constants

- go.mod
- go.sum
- io.go
- io_test.go
JIRA: https://jira.mongodb.org/browse/DEVPROD-60
To facilitate fetching paginated logs via the CLI, it is convenient to have a paginated reader that fetches subsequent pages automatically. This change essentially copies the [paginated reader from timber](https://github.com/evergreen-ci/timber/blob/main/paginated_reader.go) over.
> DEVPROD-60: paginated read closer

- slice.go
- slice_test.go
[DEVPROD-9391](https://jira.mongodb.org/browse/DEVPROD-9391)
From https://github.com/evergreen-ci/evergreen/pull/8178#discussion_r1714132423
Copied over the tests and batching implementation.
> DEVPROD-9391: create helper for making slice batches

- http.go
[DEVPROD-7885](https://jira.mongodb.org/browse/DEVPROD-7885)
This adds a retry option for invalid bodies in the RetryRequest. This is to support cases where when reading from the body gives an unexpected EOF.
> DEVPROD-7885 Add retryable option for invalid body to RetryRequest

- http.go
This adds a close statement to the body after consuming it.
> DEVPROD-7885 Close body after consuming it in retry

- file.go
- file_test.go
returning a const error so we can case on it in evergreen
will be used with this [PR](https://github.com/evergreen-ci/evergreen/pull/8490)
> DEVPROD-9735 Return walkthrough error for build

- .golangci.yml
- evergreen.yaml
- go.mod
- go.sum
- http_test.go
- makefile
[DEVPROD-3611](https://jira.mongodb.org/browse/DEVPROD-3611)
* Upgrade to Go 1.24.
* Upgrade golangci-lint to support Go 1.24.
* Remove some old linters that are now invalid.
* Fix `gofmt` lint issues.
> DEVPROD-3611: upgrade Go version

- otel.go
- otel_test.go
[DEVPROD-16412](https://jira.mongodb.org/browse/DEVPROD-16412)
`ContextWithAttributes` always overrides any pre-existing attributes when it creates the child context. But in some cases, we want to iteratively add more attributes to the same context rather than throwing out the previous attributes that have already been added. I added a method to make it easier to append rather than override the attributes associated with the context.
Added unit tests.
> DEVPROD-16412: add method to append attributes to context
